name: Worker Cron

on:
  schedule:
    - cron: "*/5 * * * *" # a cada 5 minutos
  workflow_dispatch: {}

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Call worker endpoint
        run: |
          curl -fsS "${{ secrets.WORKER_URL }}"
